#!/usr/bin/perl

#cat-strings Copyright 2004 Jason Burrell
#$Id: cat-strings 1132 2010-09-19 21:36:50Z jason $

#This program prints a string to stdout
=pod

=head1 NAME

backOffice/utilities/cat-strings - Write a L'E<acirc>ne String to STDOUT.

=head1 SYNOPSIS

cat-strings string-id

=head1 DESCRIPTION

C<cat-strings> allows one to use standard text file processing tools on L'E<acirc>ne Strings by writing the specified string to STDOUT. It is often used to inspect the value of a string or to move a single string between datasets.

=head1 ARGUMENTS

=over

=item string-id

The ID of the string to write out to STDOUT.

=back

=head1 AUTHOR

Jason Burrell

=head1 BUGS

=over

=item *

This program contains no known bugs.

=back

=head1 SEE ALSO

L<LanePOS::String>, L<update-strings>

The L'E<acirc>ne Website L<http://l-ane.net/>

=cut

BEGIN {
    use FindBin;
    use File::Spec;
    $ENV{'LaneRoot'} = File::Spec->catdir($FindBin::Bin, File::Spec->updir, File::Spec->updir); #use the correct number of updirs
    require File::Spec->catfile($ENV{'LaneRoot'}, 'config', 'init.pl');
}

use LanePOS::String;

if($#ARGV != 0)
{
    print STDERR "$0: usage: $0 string-id\n";
    exit;
}

$str = String->new;
print $str->{'data'} if $str->open($ARGV[0]);
#print STDERR $str->{'id'}, " update successful\n" if $str->save;
